import type { Metadata } from "next";
import { Atkinson_Hyperlegible } from "next/font/google";
import "./globals.css";
import Header from "@/app/header";
import Footer from "@/app/footer";
import clsx from "clsx";

const atkinson = Atkinson_Hyperlegible({
  weight: ["400", "700"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${atkinson.className} antialiased bg-ecBackgroundBody dark:bg-ecBackgroundBodyDark text-ecForeground dark:text-ecForegroundDark`}
      >
        <div
          className={clsx(
            "bg-ecBackground text-ecForeground dark:bg-ecBackgroundDark dark:text-ecForegroundDark transition-colors",
            "mb-16 mt-[4rem]"
          )}
        >
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
